( while; do cat<<EOF
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWOol;,'....:OWWX0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWOc,.            ..   .oOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMW0dl;.                         .'oOXMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMW0:'.                        ...      :0WMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMM0c;;.':,.......   ..........''...         ,XMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMNO;..   ....';:oxo;'.  ...',. .,.            oMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMM0,     .;cx0kokWMMWNX0x;.,dxc;:c:'..         .kMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMW'   .:OXWMMNKNMMMMMMMMWKKXNXK0Oxdo:'. ..     .XMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMXk.  .dOKNMMMMMMMMMMMMMMMMMMWWXK0Oxddc,... ...  oMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMN,   .dO0KNWMMMMMMMMMMMMMMMMMWWNKOkxddl;.        dMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMo    'oOKXNWWMMMMMMMMMMMMWNXKOxdkkdolcc;.         dWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMl   .'ckKXXNNNWWWWWWWXKOo:'.                       kMMMMMMMMMMMMMMMMM
MMMMMMMMMMMW,  .,lkkkxddddxxkO0Oo'.                 . .       dMMMMMMMMMMMMMMMMM
MMMMMMMMMMMX.   .'.                                          ,NMMMMMMMMMMMMMMMMM
MMMMMMMMMMMK   ..              ''                .          .OWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMX.                 kWMk.                ,;:'     .,xMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMk                .0MMWK:              clcc;'.  ,l'xWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMk              .cKWMWXKx,           .llc:;:c:..lO0NMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMW'            ';oKWMWX00Oo;;:ldxxxdooolc:;:cxXkkOdXMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMk       .;cokKkl:dOOkxddkdodooodxxdoollc:::cxKK00kWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMO     cKWMMMMXc.  ..     :0KOxlccllllllc::::lkk0WMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMN;   'kXNWWWWO.     .lOkxO0OOkdlc:cccllcc:;;dXXWMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMX.  .ck0KKKKk,...:kO0KKK00Okxolccllllccc;,;oWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWX: .lkOOOkxxkxdc;c:;,'''',,;:llooolc:;,',:NMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMK..ckKKOdl;,.  ...',;;:ccoolcclcc:;,'..';0MMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMx.,dKNN0d;,,:cloddxkOOOOkxdl::;,''....,;kMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMM0:'o0XX0xxxdddddoloodddolc:;,...    ';;dMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMo .,cddc:llc::clloodolc::;,.      .:ccoWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWO;  .....';clxkxdxkkxoc:,.      .cllcl0XWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMM0l;   .';:coddlccc:;,'.     .;lollcll..':OMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWk.    ...','.....       'cooollloo:  ..lXMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMXo;                  .:llllloddoo; .....dNMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMW,               .;:ccllodddddl. ....',:KMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk             .,:::cloodddddo.    .''',;d0XKXWMWNW
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl.          .;;;:cloooddxxx'       ..,','...,ooll
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX.        ';;:cclloooddddc           .....:dol:;
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWW:      .,;:::cclloooooo;.               ..',:ll
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN'..    .',,;;:::cclllllc.                   .....
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0      .''',,,;;::ccclcc'                   ......
EOF
done
) & sleep 15; kill $!
